package Dwarf_RPG;

public class Marteau extends Arme {
	//static double prix = 2;
	static final double RATIO_MARTEAU = 1.2;
		
	Marteau(double prix) {
		super(prix);
	}
	
	/*public String typeEquipement() {
		return("Marteau");
	}*/
	
	public void attaque_monstre(Monstre m) {
		m.prendDesDegats(prix * MONSTRE_DEGAT_RATIO * RATIO_MARTEAU);
	}
		
	public String ascii_art() {
		return 	  "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n"
				+ "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0dox0WMMMMMMMMMMMMMMMMMMMMMMMMMM\n"
				+ "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXo.  .;kWMMMMMMMMMMMMMMMMMMMMMMMMM\n"
				+ "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx.  .;::OMMMMMMMMMMMMMMMMMMMMMMMMM\n"
				+ "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWMMMMWKc'.:xxld:lNMMMMMMMMMMMMMMMMMMMMMMMM\n"
				+ "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXx;.'dNW0oOl,OMMMMMMMMMMMMMMMMMMMMMMMM\n"
				+ "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKo..c0WMMOcOk,dWMMMMMMMMMMMMMMMMMMMMMMM\n"
				+ "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWk,.,dXMMMMKclk;oWMMMMMMMMMMMMMMMMMMMMMMM\n"
				+ "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0c'':0WMMMMMWOl::kWMMMMMMMMMMMMMMMMMMMMMMM\n"
				+ "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXx;.'xNMMMMMMMMMNKXWMMMMMMMMMMMMMMMMMMMMMMMM\n"
				+ "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKl..c0WMMMMMMMMMMMWMMMMMMMMMMMMMMMMMMMMMMMMMM\n"
				+ "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMMMN0kOOOO00KNWMMMNx'.;dNMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n"
				+ "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0o:cdo:lOkc;d0XO:'.c0WMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n"
				+ "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0dccxxooONXx' ..,,.'kNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n"
				+ "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXd;;oxolxXN0c.     ';xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n"
				+ "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWOdxddc:kWXd,.      .lxONMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n"
				+ "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKkOKXO:;dl.         .:ox0NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n"
				+ "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWOc,,:;,;;.           ..'oKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n"
				+ "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNx,  .'...              cXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n"
				+ "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMXd'  .....          .'dNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n"
				+ "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKo.  ....        .lOXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n"
				+ "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKl.          .;dKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n"
				+ "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXx,        .:kXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n"
				+ "MMMMMMMMMMMMMMMMMMMMMMMMWWNXXK0Okxdoolc:;,'..         .,:ccloddxkOO0KXXNWWWMMMMMMMMMMMMMMMMMMMMMMMMM\n"
				+ "MMMMMMMMMMMMMMMMMMMMWNXKK0kxxdollcccccccccccccc::cccc::cccccccccclloddxkO00KXNWWMMMMMMMMMMMMMMMMMMMM\n"
				+ "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM";
	}
}
